server:
  port: 8081
spring:
  application:
    name=spring-security-client
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_client
    username: root
    password: pass123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update



